# Generated by Django 2.2.6 on 2019-11-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('imageid', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(unique=True)),
                ('label', models.TextField(default='')),
            ],
        ),
    ]
